from pydantic import BaseModel, Field


class CategoryBase(BaseModel):
    name: str = Field(
        min_length=1,
        max_length=120,
        description="Category name"
    )
    description: str = Field(
        min_length=1,
        max_length=300,
        description="Category description"
    )


class CategoryRequest(CategoryBase):
    pass


class CategoryResponse(CategoryBase):
    id: int = Field(description="Category unique identifier. Autogenerated")

    class Config:
        from_attributes = True
        allow_population_by_field_name = True
