from pydantic import BaseModel, Field


class LocationBase(BaseModel):
    name: str = Field(
        min_length=1,
        max_length=120,
        description="Location name"
    )
    latitude: float = Field(
        description="Describe the distance from the ecuador"
    )
    longitude: float = Field(
        description="Angular distance measured in degrees on the equator"
    )


class LocationRequest(LocationBase):
    pass


class LocationResponse(LocationBase):
    id: int = Field(description="Location unique identifier. Autogenerated")

    class Config:
        from_attributes = True
        allow_population_by_field_name = True
